### ISSUE TITLE
Error executing 'postInstallation': An error occurred.

### ISSUE THREAD

**Issue by DracoMilesX** [bitnami/bitnami-docker-ghost#59]
When trying to setup Ghost with an external database with a non default port I receive the following error.

Note that it does create the database and this error does not happen when a database with the default port is used.

'[0m
[0m[1mWelcome to the Bitnami ghost container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-ghost[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-ghost/issues[0m
[0mSend us your feedback at [1mcontainers@bitnami.com[0m
[0m
Error executing 'postInstallation': An error occurred.
Message: 'Command failed: knex-migrator-migrate --init --mgpath /opt/bitnami/ghost/current
[2017-09-27 15:54:00] [31mERROR[39m
[31m
[31mNAME: InternalServerError[39m
[31mCODE: ECONNREFUSED[39m
[31mMESSAGE: The server has encountered an error.[39m

[37mlevel:[39m[37mnormal[39m

[37mInternalServerError: The server has encountered an error.
    at new KnexMigrateError (/opt/bitnami/ghost/versions/1.9.1/node_modules/knex-migrator/lib/errors.js:7:26)
    at /opt/bitnami/ghost/versions/1.9.1/node_modules/knex-migrator/lib/database.js:52:19
    at tryCatcher (/opt/bitnami/ghost/versions/1.9.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/bitnami/ghost/versions/1.9.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/bitnami/ghost/versions/1.9.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/bitnami/ghost/versions/1.9.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/bitnami/ghost/versions/1.9.1/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/opt/bitnami/ghost/versions/1.9.1/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/bitnami/ghost/versions/1.9.1/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/bitnami/ghost/versions/1.9.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Error: connect ECONNREFUSED 172.16.4.3:3306
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
    --------------------
    at Protocol._enqueue (/opt/bitnami/ghost/versions/1.9.1/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/opt/bitnami/ghost/versions/1.9.1/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/opt/bitnami/ghost/versions/1.9.1/node_modules/mysql/lib/Connection.js:130:18)
    at /opt/bitnami/ghost/versions/1.9.1/node_modules/knex/lib/dialects/mysql/index.js:106:18
    at Promise._execute (/opt/bitnami/ghost/versions/1.9.1/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/opt/bitnami/ghost/versions/1.9.1/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/opt/bitnami/ghost/versions/1.9.1/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_MySQL.acquireRawConnection (/opt/bitnami/ghost/versions/1.9.1/node_modules/knex/lib/dialects/mysql/index.js:104:12)
    at Object.create (/opt/bitnami/ghost/versions/1.9.1/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/opt/bitnami/ghost/versions/1.9.1/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool._ensureMinimum (/opt/bitnami/ghost/versions/1.9.1/node_modules/generic-pool/lib/generic-pool.js:408:12)
    at new Pool (/opt/bitnami/ghost/versions/1.9.1/node_modules/generic-pool/lib/generic-pool.js:157:8)
    at Client_MySQL.initializePool (/opt/bitnami/ghost/versions/1.9.1/node_modules/knex/lib/client.js:269:17)
    at Client_MySQL.Client (/opt/bitnami/ghost/versions/1.9.1/node_modules/knex/lib/client.js:116:12)
    at new Client_MySQL (/opt/bitnami/ghost/versions/1.9.1/node_modules/knex/lib/dialects/mysql/index.js:62:20)
    at Knex (/opt/bitnami/ghost/versions/1.9.1/node_modules/knex/lib/index.js:60:34)[39m
[39m
[90m[39m'

I tried Joomla as well and it throws the same first part error. Didn't try Wordpress yet but it might have the same issue.

**Comment by dbarranco** [comment]
Hi @DracoMilesX 

Thank you so much for your feedback.

I have been able to reproduce this issue changing the default port of Mysql from 3306 to 3308 and I'm facing also this issue:

```
mariadb_1  | INFO  ==> Starting mariadb...
mariadb_1  | INFO  ==> Starting mysqld_safe...
mariadb_1  | 171020 09:22:20 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1  | 171020 09:22:20 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
ghost_1    | mysql-c INFO  Found MySQL server listening at mariadb:3308
ghost_1    | mysql-c INFO  MySQL server listening and working at mariadb:3308
ghost_1    | ghost   INFO  ==> Creating database...
ghost_1    | ghost   INFO  ==> Configuring Ghost...
ghost_1    | Error executing 'postInstallation': An error occurred.
ghost_1    | Message: 'Command failed: knex-migrator-migrate --init --mgpath /opt/bitnami/ghost/current
ghost_1    | [2017-10-20 09:22:24] ERROR
ghost_1    |
ghost_1    | NAME: InternalServerError
ghost_1    | CODE: ECONNREFUSED
ghost_1    | MESSAGE: The server has encountered an error.
ghost_1    |
ghost_1    | level:normal
```

I have opened an internal ticket in order to fix this.
As soon as I have any update on this I will update this thread.
I am sorry for the inconveniences.

Kind regards.

**Comment by DracoMilesX** [comment]
Thanks for the update.

I tried to do the ghost setup migrate and change the config.production.json and changed host to 192.168.1.10:3308 but in the errors it says connection refused for 127.0.0.1:3306.

Afterwards I decided to just link the mariadb container and fill in mariadb for host it says the same warning but I get the additional warning of root access is unsuccessful it appears it does not pick up the config.production.json host information or user/password information. (might be cause I make seperate user accounts for each database)

If I start Ghost with docker-compose as well it tries to connect to the docker-compose database since it says it can't login with the user/password while they do work.

**Comment by dbarranco** [comment]
Hi @DracoMilesX 

Just wanted to notify that we have released a [new version of Ghost](https://github.com/bitnami/bitnami-docker-ghost/releases/tag/1.16.1-r1) that includes a fix for this.
Make sure you configure these env vars:

```
MARIADB_HOST: Hostname for MariaDB server. Default: mariadb
MARIADB_PORT_NUMBER: Port used by MariaDB server. Default: 3306
```

In order to make Ghost to connect to your external database and create the properly `configuration.production.json`. I tested manually and it worked flawlessly.

Could you please give a try? :)


Kind regards.

**Comment by DracoMilesX** [comment]
Hi @dbarranco,

I just tried it and it is indeed working:) Adjusting config with diff user and dbs works too.

Thank you very much this issue is solved.
