### ISSUE TITLE
Error executing 'postInstallation' on all tagged versions post 1.17.1-r0

### ISSUE THREAD

**Issue by designnotdrum** [bitnami/bitnami-docker-ghost#63]
**Description**

Docker-compose up fails on "Configuring Ghost" step.

**Steps to reproduce the issue:**

1. Copy demo docker-composer.yml contents and paste into a file.
2. run docker-compose up in directory

**Describe the results you received:**

Images are pulled and containers are created as necessary, however process fails and ghost container exits upon configuration step.

```
mariadb_1  |
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | Send us your feedback at containers@bitnami.com
mariadb_1  |
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
ghost_1    |
ghost_1    | Welcome to the Bitnami ghost container
ghost_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
ghost_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
ghost_1    | Send us your feedback at containers@bitnami.com
ghost_1    |
ghost_1    | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | INFO  ==> Starting mariadb...
mariadb_1  | INFO  ==> Starting mysqld_safe...
mariadb_1  | 180113 01:43:03 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1  | 180113 01:43:03 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
ghost_1    | nami    INFO  Initializing mysql-client
ghost_1    | nami    INFO  mysql-client successfully initialized
ghost_1    | nami    INFO  Initializing ghost
ghost_1    | handler WARN  Using /opt/bitnami/ghost as working directory
ghost_1    | mysql-c INFO  Trying to connect to MySQL server
ghost_1    | mysql-c INFO  Found MySQL server listening at mariadb:3306
ghost_1    | mysql-c INFO  MySQL server listening and working at mariadb:3306
ghost_1    | ghost   INFO  ==> Configuring Database...
ghost_1    | ghost   INFO  ==> Configuring Ghost...
ghost_1    | Error executing 'postInstallation': Message: Prompts have been disabled, please provide options via command line flags
```

**Describe the results you expected:**

Expected two working containers, one ghost, one mariadb.

**Version**

- Output of `docker version`:

```
$ docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:03:51 2017
 OS/Arch:       darwin/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```

- Output of `docker info`:

```
$ docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 22
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 57
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: S4KX:YKYK:5SRW:MGQJ:NHCF:N7F5:P3EW:UQNV:WCEG:2UZ2:UTEY:TM7V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 41
 System Time: 2018-01-13T01:48:27.835244029Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
$ docker-compose version
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by Semertl** [comment]
Same issue.

**Comment by designnotdrum** [comment]
@Semertl in case you haven't tried already, I spent a few minutes last night just stepping back through available tagged versions. You can use tag `bitnami/ghost:1.17.1-r0` and it works just fine. Anything post that tag seems to be caught up in whatever issue this is.

**Comment by grantbachman** [comment]
I'm experiencing the same issue. This affects the latest Kubernetes stable/ghost helm chart as well. I enabled tracing on nami and got the following output, but it doesn't mean much to me.

```
I have no name!@9d06adb98649:/opt/bitnami/ghost$ nami --log-level=trace initialize ghost
nami    INFO  Initializing ghost
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at docker.for.mac.localhost:3306
mysql-c TRACE [canConnect] Testing connection with 'bn_ghost' user
mysql-c TRACE [showDatabases] Getting databases for 'bn_ghost' user
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hdocker.for.mac.localhost -ubn_ghost -e SHOW DATABASES;
mysql-c TRACE [execute] Result: {"code":0,"stdout":"bitnami_ghost\ninformation_schema\n","stderr":""}
mysql-c TRACE [showDatabases] Databases: bitnami_ghost
information_schema

mysql-c TRACE [canConnect] Connection with 'bn_ghost' user is successful
mysql-c INFO  MySQL server listening and working at docker.for.mac.localhost:3306
ghost   INFO  ==> Configuring Database...
ghost   INFO  ==> Configuring Ghost...
ghost   TRACE [runProgram] Executing: ghost setup,--no-setup-nginx,--no-setup-ssl,--no-setup-mysql,--no-setup-systemd,--no-setup-linux-user,--url,http://localhost:2368,--ip,0.0.0.0,--port,2368,--log,file,--process,local,--no-prompt,--no-start,--no-enable
Error executing 'postInstallation': Message: Prompts have been disabled, please provide options via command line flags


nami    TRACE Error: Error executing 'postInstallation': Message: Prompts have been disabled, please provide options via command line flags


    at runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/run-program.js:223:14)
    at Object.runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/index.js:63:12)
    at Object.$app.helpers.configureGhost (/.nami/components/com.bitnami.ghost/helpers.js:123:7)
    at Service.$app.postInstallation (/.nami/components/com.bitnami.ghost/main.js:44:18)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
    at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
    at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
```

**Comment by dbarranco** [comment]
Hi @grantbachman @designnotdrum @Semertl 

Thank you so much for reporting this, I have been able to reproduce this locally just doing a docker-compose up of the container. The execution with `NAMI_LOG_LEVEL=trace` has been quite useful for me :)

We will release a new revision of the Ghost image as soon as possible fixing this. I have created an internal task with high priority.

Sorry for the inconveniences this may case to you.
Best regards.

**Comment by dbarranco** [comment]
Hi @grantbachman @designnotdrum @Semertl 

We have just released the [1.19.2-1](https://github.com/bitnami/bitnami-docker-ghost/releases/tag/1.19.2-r1) revision that should address this problem.

Could you please confirm that this issue is solved?

Best regards.

**Comment by grantbachman** [comment]
I just tested the new image and it works for me! Thanks for the quick turnaround time, @dbarranco!

**Comment by designnotdrum** [comment]
Yep, new image worked for me as well. Thanks for the quick turnaround @dbarranco
