### ISSUE TITLE
Cannot Connect to fresh Remote DB on Startup

### ISSUE THREAD

**Issue by RobbieMcKinstry** [bitnami/bitnami-docker-ghost#92]
**Description**

**Summary:** Ghost fails to connect to any fresh remote database on startup.

At startup, when Ghost attempts to create the Admin user, it fails to connect to the database. The script executed to configure the database is hard-coded to use `127.0.0.1` as the port number. As a result, Ghost will not connect to remote databases; `MARIADB_HOST` is ignored.

**Steps to reproduce the issue:**

1. Provision a MySQL database **NOT** located at `127.0.0.1`. In my case, I'm using a [DigitalOcean managed database](https://cloud.digitalocean.com/databases).

2. Create a new user and a new database for Ghost exclusive use.

3. Confirm that you can connect to this database locally. I used the `mysql-client` to confirm this.
```
mysql \
    -h $MARIADB_HOST \
    -u $GHOST_DATABASE_USER \
    --password=$GHOST_DATABASE_PASSWORD \
    -D $GHOST_DATABASE_NAME \
    -P $MARIADB_PORT_NUMBER
```

4. Start the Bitnami Ghost Docker container using the same configuration.

```
docker run -d 
    --name ghost \
    -p 8080:80 \
    -p 4443:443 \
    -e GHOST_DATABASE_USER=$GHOST_DATABASE_USER \
    -e GHOST_DATABASE_NAME=$GHOST_DATABASE_NAME \
    -e MARIADB_PORT_NUMBER=$MARIADB_PORT_NUMBER \
    -e GHOST_DATABASE_PASSWORD=$GHOST_DATABASE_PASSWORD \
    -e MARIADB_HOST=$MARIADB_HOST \
    bitnami/ghost
```

5. Observe the logs. Wait until the container as crashed (approximately 5 minutes). 

```
docker logs --follow $CONTAINER_ID
```

**Describe the results you received:**

Initially, the MySQL client successfully connects to the database. The host is configured successfully. Then, Ghost attempts to create an Admin user. At this point, the script makes no more forward progress, and errors after a number of failed attempts to connect to the database.

**Describe the results you expected:**

I expected initialization to continue uninterrupted, for the admin user to be created, and for the webserver to launch and accept connections.

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm including a small collection of screenshots to demonstrate the issue.

<img width="1279" alt="Screen Shot 2020-10-04 at 3 49 09 PM" src="https://user-images.githubusercontent.com/4955075/95026740-82bdc000-0661-11eb-9a53-049ad9c5290b.png">

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:41:33 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:27 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 14
  Running: 0
  Paused: 0
  Stopped: 14
 Images: 81
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: BEH6:54NM:5EVQ:HKJJ:FLFF:35ZH:YFSG:NEVX:IR4Z:RV6Z:F2ZZ:K52X
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 52
  System Time: 2020-10-04T20:16:48.00577328Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

* I also attempted to use the parameters which would automatically create a new MySQL database and user on initialization. For reference, these parameters are:

```
MARIADB_ROOT_USER
MARIADB_ROOT_PASSWORD
MYSQL_CLIENT_CREATE_DATABASE_NAME
MYSQL_CLIENT_CREATE_DATABASE_USER
MYSQL_CLIENT_CREATE_DATABASE_PASSWORD
```

* I also experienced this issue using the Bitnami Helm chart.

* About a month ago, I was able to trace this error to a JavaScript file, named something like `helper.js`, which had the loopback IP hard-coded as part of the configuration step. I would love to be able to point you to a line number, but unfortunately I was unable to find the corresponding source code online at the time, and I can't recreate this trace anymore. I'll keep looking.

* I have to imagine that this bug prevents this image from ever connecting to a remote database. I would bet that using a managed database is a common production use case.

**Comment by RobbieMcKinstry** [comment]
Whoops, forgot to upload the screenshots. Redacting my credentials, and uploading them now...

**Comment by miguelaeh** [comment]
Hi @RobbieMcKinstry ,
It fails to wait for the webserver to be up, that's why it looks for `127.0.0.1`. It seems that for some reason the server is not properly running to make an http POST to the endpoint that creates the admin user. Could you try to run the container with `NAMI_DEBUG=1` and `NAMI_LOG_LEVEL=trace8` ?

**Comment by RobbieMcKinstry** [comment]
Hi @miguelaeh, thanks for the quick reply! Sure!

FYI I redacted the username, password, database name, and MariaDB host once again. If you think it might be beneficial to see some of those values, I can post some of them. There's nothing special or tricky about them.

Here's the new output:

```
app-entrypoint.sh 02:53:39.52
app-entrypoint.sh 02:53:39.53 Welcome to the Bitnami ghost container
app-entrypoint.sh 02:53:39.53 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-ghost
app-entrypoint.sh 02:53:39.53 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-ghost/issues
app-entrypoint.sh 02:53:39.53
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf                                                                            [142/465]
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
mysql-c TRACE [normalize] File normalization: tmp -> /opt/bitnami/mysql/tmp
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
node    TRACE [normalize] File normalization: data -> /opt/bitnami/node/data
node    TRACE [normalize] File normalization: logs -> /opt/bitnami/node/logs
node    TRACE [normalize] File normalization: tmp -> /opt/bitnami/node/tmp
node    TRACE [normalize] File normalization: conf -> /opt/bitnami/node/conf
node    TRACE [normalize] File normalization: lib -> /opt/bitnami/node/lib
node    TRACE [normalize] File normalization: bin -> /opt/bitnami/node/bin
ghost   TRACE [normalize] File normalization: conf -> /opt/bitnami/ghost/conf
ghost   TRACE [normalize] File normalization: conf -> /opt/bitnami/ghost/conf
ghost   TRACE [normalize] File normalization: bin -> /opt/bitnami/ghost/bin
ghost   TRACE [normalize] File normalization: bin -> /opt/bitnami/ghost/bin
ghost   TRACE [normalize] File normalization: data -> /opt/bitnami/ghost/data
ghost   TRACE [normalize] File normalization: data -> /opt/bitnami/ghost/data
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: data -> /opt/bitnami/ghost/data                                                                            [106/465]
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: lib -> /opt/bitnami/ghost/lib
ghost   TRACE [normalize] File normalization: lib -> /opt/bitnami/ghost/lib
ghost   TRACE [normalize] File normalization: conf -> /opt/bitnami/ghost/conf
ghost   TRACE [normalize] File normalization: conf -> /opt/bitnami/ghost/conf
ghost   TRACE [normalize] File normalization: bin -> /opt/bitnami/ghost/bin
ghost   TRACE [normalize] File normalization: bin -> /opt/bitnami/ghost/bin
ghost   TRACE [normalize] File normalization: data -> /opt/bitnami/ghost/data
ghost   TRACE [normalize] File normalization: data -> /opt/bitnami/ghost/data
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: lib -> /opt/bitnami/ghost/lib
ghost   TRACE [normalize] File normalization: lib -> /opt/bitnami/ghost/lib
ghost   TRACE [normalize] File normalization: conf -> /opt/bitnami/ghost/conf
ghost   TRACE [normalize] File normalization: conf -> /opt/bitnami/ghost/conf
ghost   TRACE [normalize] File normalization: bin -> /opt/bitnami/ghost/bin
ghost   TRACE [normalize] File normalization: bin -> /opt/bitnami/ghost/bin
ghost   TRACE [normalize] File normalization: data -> /opt/bitnami/ghost/data
ghost   TRACE [normalize] File normalization: data -> /opt/bitnami/ghost/data
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: lib -> /opt/bitnami/ghost/lib
ghost   TRACE [normalize] File normalization: lib -> /opt/bitnami/ghost/lib
ghost   TRACE [normalize] File normalization: conf -> /opt/bitnami/ghost/conf
ghost   TRACE [normalize] File normalization: conf -> /opt/bitnami/ghost/conf
ghost   TRACE [normalize] File normalization: bin -> /opt/bitnami/ghost/bin
ghost   TRACE [normalize] File normalization: bin -> /opt/bitnami/ghost/bin
ghost   TRACE [normalize] File normalization: data -> /opt/bitnami/ghost/data
ghost   TRACE [normalize] File normalization: data -> /opt/bitnami/ghost/data
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: lib -> /opt/bitnami/ghost/lib
ghost   TRACE [normalize] File normalization: lib -> /opt/bitnami/ghost/lib
ghost   TRACE [normalize] File normalization: conf -> /opt/bitnami/ghost/conf
ghost   TRACE [normalize] File normalization: conf -> /opt/bitnami/ghost/conf
ghost   TRACE [normalize] File normalization: bin -> /opt/bitnami/ghost/bin
ghost   TRACE [normalize] File normalization: conf -> /opt/bitnami/ghost/conf                                                                             [70/465]
ghost   TRACE [normalize] File normalization: bin -> /opt/bitnami/ghost/bin
ghost   TRACE [normalize] File normalization: bin -> /opt/bitnami/ghost/bin
ghost   TRACE [normalize] File normalization: data -> /opt/bitnami/ghost/data
ghost   TRACE [normalize] File normalization: data -> /opt/bitnami/ghost/data
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: lib -> /opt/bitnami/ghost/lib
ghost   TRACE [normalize] File normalization: lib -> /opt/bitnami/ghost/lib
nami    INFO  Initializing ghost
ghost   TRACE [delete] File normalization: /opt/bitnami/ghost/logs -> /opt/bitnami/ghost/logs
ghost   TRACE [mkdir] File normalization: /opt/bitnami/ghost/content/logs -> /opt/bitnami/ghost/content/logs
handler WARN  Using /opt/bitnami/ghost as working directory
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
mysql-c TRACE [normalize] File normalization: conf -> /opt/bitnami/mysql/conf
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: bin -> /opt/bitnami/mysql/bin
mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
mysql-c TRACE [normalize] File normalization: data -> /opt/bitnami/mysql/data
mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
mysql-c TRACE [normalize] File normalization: logs -> /opt/bitnami/mysql/logs
mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
mysql-c TRACE [normalize] File normalization: lib -> /opt/bitnami/mysql/lib
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [mkdir] File normalization: /opt/bitnami/ghost/logs -> /opt/bitnami/ghost/logs
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at ghost-database-do-user-331984-0.a.db.ondigitalocean.com:25060
mysql-c TRACE [canConnect] Testing connection with '$REDACTED_DATABASE_USER' user
mysql-c TRACE [showDatabases] Getting databases for '$REDACTED_DATABASE_USER' user
mysql-c TRACE [execute] Executing: mysql -N -P 25060 -h$REDACTED_MARIADB_HOST -u$REDACTED_DATABASE_USER -p$REDACTED_DATABASE_PASSWORD -e SHOW DATABASES;
mysql-c TRACE [execute] Result: {"code":0,"stdout":"$REDACTED_DATABASE_NAME\ninformation_schema\n","stderr":""}
mysql-c TRACE [showDatabases] Databases: $REDACTED_DATABASE_NAME
information_schema

mysql-c TRACE [canConnect] Connection with '$REDACTED_DATABASE_USER' user is successful
mysql-c INFO  MySQL server listening and working at ghost-database-do-user-331984-0.a.db.ondigitalocean.com:25060
ghost   TRACE [exists] File normalization: /bitnami/ghost/.initialized -> /bitnami/ghost/.initialized
ghost   INFO  ==> Configuring Database...
ghost   TRACE [exists] File normalization: /bitnami/ghost/.initialized -> /bitnami/ghost/.initialized                                                     [34/465]
ghost   INFO  ==> Configuring Database...
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/config.production.json -> /opt/bitnami/ghost/config.production.json
ghost   INFO  ==> Configuring Ghost...
ghost   TRACE [runProgram] Executing: ghost setup,--no-setup-nginx,--no-setup-ssl,--no-setup-mysql,--no-setup-systemd,--no-setup-linux-user,--url,http://172.17.0.
2,--ip,0.0.0.0,--port,2368,--log,file,--process,local,--no-prompt,--no-start,--no-enable
ghost   TRACE [runProgram] Executing internal command: ghost ["setup","--no-setup-nginx","--no-setup-ssl","--no-setup-mysql","--no-setup-systemd","--no-setup-linu
x-user","--url","http://172.17.0.2","--ip","0.0.0.0","--port",2368,"--log","file","--process","local","--no-prompt","--no-start","--no-enable"]
ghost   TRACE [runProgram] RESULT: {"code":0,"stderr":"","stdout":"- Inspecting operating system\n[02:53:47] Checking for Ghost-CLI updates [started]\n[02:53:48]
Checking for Ghost-CLI updates [completed]\n[02:53:48] Configuring Ghost [started]\n[02:53:48] Configuring Ghost [completed]\n[02:53:48] Setting up instance [star
ted]\n[02:53:48] Setting up instance [completed]\n\nGhost uses direct mail by default. To set up an alternative email method read our docs at https://ghost.org/do
cs/concepts/config/#mail\n\n------------------------------------------------------------------------------\n\nGhost was installed successfully! To complete setup
of your publication, visit: \n\n    http://172.17.0.2/ghost/\n\n"}
ghost   INFO  ==> Configuring host...
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/config.production.json -> /opt/bitnami/ghost/config.production.json
ghost   TRACE [read] File normalization: /opt/bitnami/ghost/config.production.json -> /opt/bitnami/ghost/config.production.json
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/config.production.json -> /opt/bitnami/ghost/config.production.json
ghost   TRACE [write] File normalization: /opt/bitnami/ghost/config.production.json -> /opt/bitnami/ghost/config.production.json
ghost   INFO  ==> Restarting service...
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/logs/ghost.log -> /opt/bitnami/ghost/logs/ghost.log
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/logs/ghost.log -> /opt/bitnami/ghost/logs/ghost.log
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/logs/ghost.log -> /opt/bitnami/ghost/logs/ghost.log
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/logs/ghost.log -> /opt/bitnami/ghost/logs/ghost.log
ghost   TRACE [normalize] File normalization: logs -> /opt/bitnami/ghost/logs
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/logs/ghost.log -> /opt/bitnami/ghost/logs/ghost.log
ghost   TRACE [exists] File normalization: /opt/bitnami/ghost/logs -> /opt/bitnami/ghost/logs
ghost   TRACE [exists] File normalization: /tmp -> /tmp
ghost   TRACE [exists] File normalization: /tmp -> /tmp
ghost   TRACE [runProgram] Executing: null ghost start
ghost   TRACE [runProgram] Executing internal command: '/bin/sh' ["-c","ghost start &"]
ghost   TRACE [runProgram] RESULT: {"code":0,"stderr":"","stdout":""}
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE [normalize] File normalization: /opt/bitnami/ghost/.ghostpid -> /opt/bitnami/ghost/.ghostpid
ghost   TRACE code: 0
ghost   TRACE stdout:

ghost   TRACE stderr:

ghost   INFO  ==> Host configured successfully!
ghost   INFO  ==> Creating admin user...
ghost   DEBUG Waiting for service at 127.0.0.1:2368...
Error executing 'postInstallation': Failed to connect to 127.0.0.1:2368 after 36 tries
nami    TRACE Error: Error executing 'postInstallation': Failed to connect to 127.0.0.1:2368 after 36 tries
    at Object.waitForService (/.nami/components/com.bitnami.ghost/lib/network.js:77:23)
    at Object.$app.helpers.createAdminUser (/.nami/components/com.bitnami.ghost/helpers.js:13:20)
    at Service.$app.postInstallation (/.nami/components/com.bitnami.ghost/main.js:52:18)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
    at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
```

**Comment by RobbieMcKinstry** [comment]
Looks like `ghost start` is backgrounded without error, and I didn't see any errors occurring before that point.

**Comment by RobbieMcKinstry** [comment]
I tried to look at the ghost logs to see if the backgrounded process was failing but it seems the log directory is circularly symbolically linked? Perhaps linked to `/opt/bitnami/ghost/logs -> /opt/bitnami/ghost/content/logs` and back again?

```
# Commit the failed container, so we can autopsy it:
docker commit 4943c9566ec7733a2fe09b4d67dca8 my-broken-container
# Connect to the container's shell:
docker run -it my-broken-container /bin/bash
# Inspect the log files:
ls /opt/bitnami/ghost/logs
```
Yields the following error from the shell:
```
ls: cannot access '/opt/bitnami/ghost/logs': Too many levels of symbolic links
```

**Comment by miguelaeh** [comment]
Hi @RobbieMcKinstry ,
I am trying to reproduce the issue with docker-compose but I am not able to do it.
I am using the following docker-compose:
```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_ghost
      - MARIADB_DATABASE=bitnami_ghost
    volumes:
      - 'mariadb_data:/bitnami'
  ghost:
    image: 'docker.io/bitnami/ghost:3-debian-10'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_HOST=localhost
    ports:
      - '80:2368'
    volumes:
      - 'ghost_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local
```

Which version of the image are you using?

Apart from that, the circular symlinks appear because the container is not properly initialized yet. Once it finished the initialization the symlinks will be correct:
```
I have no name!@30bd8854602d:/opt/bitnami/ghost$ ls -l /opt/bitnami/ghost
total 24
lrwxrwxrwx 1 root root   52 Oct  5 19:23 bin -> /opt/bitnami/ghost/versions/3.35.3/node_modules/.bin
lrwxrwxrwx 1 1001 root   37 Oct  6 07:09 config.production.json -> /bitnami/ghost/config.production.json
lrwxrwxrwx 1 1001 root   22 Oct  6 07:09 content -> /bitnami/ghost/content
lrwxrwxrwx 1 root root   34 Oct  5 19:23 current -> /opt/bitnami/ghost/versions/3.35.3
drwxr-xr-x 2 1001 root 4096 Oct  6 07:09 extra
drwxrwxrwx 2 root root 4096 Oct  5 19:23 licenses
drwxrwxrwx 2 1001 root 4096 Oct  6 07:09 logs
-rw-r--r-- 1 1001 root   11 Oct  6 07:09 nss_group
-rw-r--r-- 1 1001 root   51 Oct  6 07:09 nss_passwd
drwxrwxrwx 3 root root 4096 Oct  5 19:23 versions
I have no name!@30bd8854602d:/opt/bitnami/ghost$ ls -l /opt/bitnami/ghost/content
lrwxrwxrwx 1 1001 root 22 Oct  6 07:09 /opt/bitnami/ghost/content -> /bitnami/ghost/content
I have no name!@30bd8854602d:/opt/bitnami/ghost$ ls -l /bitnami/ghost/content
total 20
drwxr-xr-x 2 1001 root 4096 Oct  6 07:09 apps
drwxr-xr-x 2 1001 root 4096 Oct  6 07:09 data
drwxr-xr-x 2 1001 root 4096 Oct  6 07:09 images
lrwxrwxrwx 1 1001 root   23 Oct  6 07:09 logs -> /opt/bitnami/ghost/logs
drwxr-xr-x 2 1001 root 4096 Oct  6 07:09 settings
drwxr-xr-x 2 1001 root 4096 Oct  6 07:09 themes
```

Also, probably not related, but in you command you have:
```
    -p 8080:80 \
    -p 4443:443 \
```

Note that the Ghost's port is `2368` not `80`.

**Comment by RobbieMcKinstry** [comment]
Hi @miguelaeh,

Thanks for catching my incorrect port. I was able to reproduce the issue using the `docker-compose.yml` posted below. Of note, I realized that the database I was connecting to on DigitalOcean was using MySQL 8, which is not supported by Ghost at this time. See [this issue](https://github.com/TryGhost/Ghost-CLI/issues/833) for more detail.

Does this Bitnami use [a work-around](https://dabbler.dev/posts/2020/05/31/) to achieve compatibility?

Regardless, I modified your `docker-compose.yml` to use MySQL `v5.7.31`, which is presently supported by Ghost. Switching from MariaDB to MySQL DB seemed to introduce the bug, as the `docker-compose.yml` file you provided works fine on my machine.

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mysql:5.7.31'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bn_ghost
      - MYSQL_DATABASE=bitnami_ghost
    volumes:
      - 'mariadb_data:/bitnami'
  ghost:
    image: 'docker.io/bitnami/ghost:3-debian-10'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_HOST=localhost
    ports:
      - '80:2368'
    volumes:
      - 'ghost_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local
```

Here's the diff between the `docker-compose.yml` file you provided and my modification.

```
<     image: 'docker.io/bitnami/mariadb:10.3-debian-10'
---
>     image: 'docker.io/bitnami/mysql:5.7.31'
<       - MARIADB_USER=bn_ghost
<       - MARIADB_DATABASE=bitnami_ghost
---
>       - MYSQL_USER=bn_ghost
>       - MYSQL_DATABASE=bitnami_ghost
```

**Comment by miguelaeh** [comment]
Hi @RobbieMcKinstry ,

> Does this Bitnami use a work-around to achieve compatibility?

We package Ghost as it is, without any modification. Because of that, the compatibility with MySQL and MariaDB should be the same as a normal Ghost.

I have tested you docker-compose and it has worked fine for me.
Could yo try it in a different folder or removing the volumes with `docker-compose down -v` before the new `docker-compose up`
