### ISSUE TITLE
Sudo error after adding storage adapter

### ISSUE THREAD

**Issue by DevOpsFu** [bitnami/bitnami-docker-ghost#96]
**Description**

I'm trying to add the Azure Storage adapter to the Bitnami Ghost container. When running the resulting container, I receive an error from the `postInstallation` phase.

**Steps to reproduce the issue:**

1. Build a new container like so:

```
FROM bitnami/ghost:latest
USER root
RUN npm install ghost-azure-storage --unsafe-perm

USER 1001
RUN cp -vR node_modules/ghost-azure-storage ./current/core/server/adapters/storage
```

2. Run the container with some sensible env vars

**Describe the results you received:**

```
ghost   INFO  ==> Configuring Database...
ghost   INFO  ==> Configuring Ghost...
Error executing 'postInstallation': An error occurred.
Message: 'Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  chown -R ghost:ghost /.config
sudo: you do not exist in the passwd database
```

**Describe the results you expected:**

I would expect Ghost to boot successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:49:35 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 24
  Running: 15
  Paused: 0
  Stopped: 9
 Images: 17
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.114
 Operating System: Buildroot 2019.02.11
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.742GiB
 Name: minikube
 ID: YGCK:VOQC:FLSY:KMPM:5ZV6:HCHQ:JRWK:AL3T:YJRX:PXCU:42D6:KWUW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=hyperv
 Experimental: false
 Insecure Registries:
  10.96.0.0/12
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

N/A

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by FraPazGal** [comment]
Hello @DevOpsFu,

Thanks for reaching out! It seems `ghost-azure-storage` needs to run as `ghost` user, which is not present on `etc/sudoers`. Please try adding the following line to your `Dockerfile`:

```Dockerfile
FROM bitnami/ghost:latest
USER root
RUN npm install ghost-azure-storage --unsafe-perm
RUN useradd ghost

...
```

**Comment by DevOpsFu** [comment]
Thanks for getting back to me @FraPazGal!

Adding that seems to have gotten things a little further, but it's still not working unfortunately:

```
ghost   INFO  ==> Configuring Ghost...
ghost   TRACE [runProgram] Executing: ghost setup,--no-setup-nginx,--no-setup-ssl,--no-setup-mysql,--no-setup-systemd,--no-setup-linux-user,--url,http://mysite/,--ip,0.0.0.0,--port,2368,--log,file,--process,local,--no-prompt,--no-start,--no-enable
ghost   TRACE [runProgram] Executing internal command: ghost ["setup","--no-setup-nginx","--no-setup-ssl","--no-setup-mysql","--no-setup-systemd","--no-setup-linux-user","--url","http://mysite/","--ip","0.0.0.0","--port",2368,"--log","file","--process","local","--no-prompt","--no-start","--no-enable"]
ghost   TRACE [runProgram] RESULT: {"code":1,"stderr":"/opt/bitnami/ghost/versions/3.40.1/node_modules/ghost-cli/lib/ui/index.js:148\n            throw new errors.SystemError('Prompts have been disabled, all options must be provided via command line flags');\n            ^\n\nSystemError: Prompts have been disabled, all options must be provided via command line flags\n    at UI.prompt (/opt/bitnami/ghost/versions/3.40.1/node_modules/ghost-cli/lib/ui/index.js:148:19)\n    at Socket.<anonymous> (/opt/bitnami/ghost/versions/3.40.1/node_modules/ghost-cli/lib/ui/index.js:248:22)\n    at Socket.emit (events.js:327:22)\n    at addChunk (_stream_readable.js:309:12)\n    at readableAddChunk (_stream_readable.js:284:9)\n    at Socket.Readable.push (_stream_readable.js:223:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {\n  options: {\n    message: 'Prompts have been disabled, all options must be provided via command line flags'\n  },\n  logMessageOnly: undefined,\n  help: 'You can always refer to https://ghost.org/docs/api/ghost-cli/ for troubleshooting.',\n  err: {}\n}\n","stdout":"- Inspecting operating system\n[13:19:21] Checking for Ghost-CLI updates [started]\n[13:19:21] Checking for Ghost-CLI updates [completed]\n[13:19:21] Ensuring correct ~/.config folder ownership [started]\n+ sudo chown -R ghost:ghost /.config\n"}
Error executing 'postInstallation': /opt/bitnami/ghost/versions/3.40.1/node_modules/ghost-cli/lib/ui/index.js:148
            throw new errors.SystemError('Prompts have been disabled, all options must be provided via command line flags');
            ^

SystemError: Prompts have been disabled, all options must be provided via command line flags
    at UI.prompt (/opt/bitnami/ghost/versions/3.40.1/node_modules/ghost-cli/lib/ui/index.js:148:19)
    at Socket.<anonymous> (/opt/bitnami/ghost/versions/3.40.1/node_modules/ghost-cli/lib/ui/index.js:248:22)
    at Socket.emit (events.js:327:22)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
  options: {
    message: 'Prompts have been disabled, all options must be provided via command line flags'
  },
  logMessageOnly: undefined,
  help: 'You can always refer to https://ghost.org/docs/api/ghost-cli/ for troubleshooting.',
  err: {}
}

nami    TRACE Error: Error executing 'postInstallation': /opt/bitnami/ghost/versions/3.40.1/node_modules/ghost-cli/lib/ui/index.js:148
            throw new errors.SystemError('Prompts have been disabled, all options must be provided via command line flags');
            ^

SystemError: Prompts have been disabled, all options must be provided via command line flags
    at UI.prompt (/opt/bitnami/ghost/versions/3.40.1/node_modules/ghost-cli/lib/ui/index.js:148:19)
    at Socket.<anonymous> (/opt/bitnami/ghost/versions/3.40.1/node_modules/ghost-cli/lib/ui/index.js:248:22)
    at Socket.emit (events.js:327:22)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
  options: {
    message: 'Prompts have been disabled, all options must be provided via command line flags'
  },
  logMessageOnly: undefined,
  help: 'You can always refer to https://ghost.org/docs/api/ghost-cli/ for troubleshooting.',
  err: {}
}

    at runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/run-program.js:223:14)
    at Object.runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/index.js:63:12)
    at Object.$app.helpers.configureGhost (/.nami/components/com.bitnami.ghost/helpers.js:142:7)
    at Service.$app.postInstallation (/.nami/components/com.bitnami.ghost/main.js:42:18)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
```

**Comment by DevOpsFu** [comment]
Further to the above, I've tried running the ghost command manually and it looks like the error might still be stemming from the following:

```
sudo chown -R ghost:ghost /.config
```

Which, when executed by the `ghost` user, prompts for the user's password, which I guess is why we see the `Prompts are disabled` error

**Comment by FraPazGal** [comment]
Yes @DevOpsFu, that seems to be the reason. Please try adding the following line to the `Dockerfile`:

```Dockerfile
...
RUN useradd ghost
RUN echo "ghost ALL=(ALL:ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/ghost
...
```

That should make the system stop prompting for the `ghost` user password.

**Comment by DevOpsFu** [comment]
@FraPazGal That's got it, thank you for your help!
